spring:
  application:
    name: doctor-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}?serverTimezone=UTC&useLegacyDatetimeCode=false
    name: med_care_demo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
  grpc:
    server:
      port: 9092
server:
  port: 9081